### ISSUE TITLE
Bump The Server Reminders

### ISSUE THREAD

**Issue by DeveloperDrago** [Discord-FurDevs/FurDevs-Bot#15]
When a Spot opens to Bump the Server for Discord.me and Disboard DM Drago to bump the server to stop forgetting about it

**Comment by thetayloredman** [comment]
Kinda seems like API abuse to be sending a DM on an interval.. not sure.

**Comment by ElectricDaAluki** [comment]
> Kinda seems like API abuse to be sending a DM on an interval.. not sure.

You are API Abuse.
Joking aside though, i don't think so. But @DeveloperDrago, Stop being lazy.

**Comment by DeveloperDrago** [comment]
Lmao I'm trying aaaaa I seen other server do it for discord.me for a while so um might aswell lmfao

**Comment by thetayloredman** [comment]
Yep. I've seen people saying not to do stuff on an interval if you don't want the banhammer.

**Comment by DeveloperDrago** [comment]
@thetayloredman https://www.reddit.com/r/Discord_Bots/comments/jqgf0p/is_message_being_sent_in_hourly_intervals/

**Comment by thetayloredman** [comment]
Not a true reply.

First of all, that's /r/Discord_Bots, not the OFFICIAL /r/discord.

Second of all, you really should file a [Trust And Safety -> General Policy Question request](https://support.discord.com/hc/en-us/requests/new) about this. It's a VERY gray area.

**Comment by DeveloperDrago** [comment]
Okey XP

**Comment by DeveloperDrago** [comment]
Sented will check back on it later

**Comment by DeveloperDrago** [comment]
Bumping Reminders is completed in 55acf44b281540061d1ed6a51c89e0a3e3fcb068

**Comment by thetayloredman** [comment]
@DeveloperDrago idea: use pull requests and "Closes #15" keywords to auto-close, and if you pasted the entire commit hash there's no need just use the first 6-7 chars

**Comment by DeveloperDrago** [comment]
Ohh good idea
