### ISSUE TITLE
add command to verify users

### ISSUE THREAD

**Issue by codic12** [Discord-FurDevs/FurDevs-Bot#17]

**Comment by Furry** [comment]
@codic12 @DeveloperDrago How are you guys planning on implementing this? I could help out if you'd like.

**Comment by codic12** [comment]
Seems to been implemented at https://github.com/Discord-FurDevs/FurDevs-Bot/commit/97e68c4644a19cb092748b613c012ac84f06e0cb, and the commits above it in the hiearchy

**Comment by DeveloperDrago** [comment]
Hello @Furry thanks for helping by, so what I was thinking so far was have it so when the user DMs the Modmail for our server answering four question a staff member will look into the questions and make sure they are appropriate and valid you could say and if the user is all good a staff member will do ">verify < username > [ answers to the verification ] then it'll get logged into the database for security reasons and then the verified members role then gets applied to the member and the bot will welcome that user

**Comment by DeveloperDrago** [comment]
It's kinda temporary since I plan to add a verification system that DMs the users the questions that you provided during a setup process which I will also add ( and if the user's DM is disabled it'll make a channel for that user and continue the process from there ) then an embed will get created with a checkmark, an X, or Hammer and a staff member can react to those to either accept, deny or ban

**Comment by DeveloperDrago** [comment]
> Seems to been implemented at https://github.com/Discord-FurDevs/FurDevs-Bot/commit/97e68c4644a19cb092748b613c012ac84f06e0cb, and the commits above it in the hierarchy

Codic, I mean kinda I was developing it today still was broken probably something with the username resolver

**Comment by Furry** [comment]
Ah, okay that makes sense @DeveloperDrago! I have something similar going with my old bot. On a quick side note while you're here though, in https://github.com/Discord-FurDevs/FurDevs-Bot/blob/0055a168418cba19c0dbe4d8b2c2c9cfa7e36bf0/index.js#L131 this line, I'm not really sure what's going on. I'm running node v14.4.0, and it seems your use of event.bind() isn't working for me?

**Comment by DeveloperDrago** [comment]
Hmm that's interesting at the moment I'm not on my laptop but what I could say is it could be the node version maybe not too entirely sure but I'll look into this once I can

**Comment by Furry** [comment]
My bad, I found the issue! It was completely my fault, I had modified the importing of files to a recursive system, so it was throwing off the parsing of the event name.

**Comment by DeveloperDrago** [comment]
Ahhh yikes

**Comment by DeveloperDrago** [comment]
Verification Command completed in a57168b32b24e2e146cc78b6da5ea20bc1be1995 Verification System ( #9 ) Will be worked on later to replace the verification command

**Comment by codic12** [comment]
lol

**Comment by thetayloredman** [comment]
> Verification Command completed in [a57168b](https://github.com/Discord-FurDevs/FurDevs-Bot/commit/a57168b32b24e2e146cc78b6da5ea20bc1be1995) Verification System ( #9 ) Will be worked on later to replace the verification command

In the future make a57a68b's description contain "Closes #17" and it would close for you
