### ISSUE TITLE
question about your commits

### ISSUE THREAD

**Issue by thetayloredman** [Discord-FurDevs/FurDevs-Bot#27]
Which do you use?

- graphical git UI
- `git commit -m 'message'`
- `git commit` -> vim -> enter message
- other, please specify

**Comment by thetayloredman** [comment]
@DeveloperDrago

**Comment by DeveloperDrago** [comment]
Graphical Git Ui - Github Desktop since I haven't really experienced lots of conflictions/problems

I used to use `git commit -m "message"`

**Comment by thetayloredman** [comment]
good. please start using the Extra Description, and when you use terminal, let it use vim, because yoou do
```
commit message

extra description

```
to add a desc

**Comment by thetayloredman** [comment]
And maybe better commit messages than c355a86 (`Yes.`)

**Comment by DeveloperDrago** [comment]
Okay I'll _try_ to make better commits usually I don't really bother with commits messages I just add like jokes or really unnecessary stuff lol

**Comment by thetayloredman** [comment]
[thetayloredman/ProtoBot](https://github.com/thetayloredman/ProtoBot) **PRIVATE** example of bad commit messages
[JSCord/core](https://github.com/JSCord/core] **PUBLIC** example of better commit messages

**Comment by DeveloperDrago** [comment]
Ah okay

**Comment by ElectricDaAluki** [comment]
should it really matter about how commit messages are made?

**Comment by thetayloredman** [comment]
idk i just encourage good ones because it makes projects look good 🤷

**Comment by thetayloredman** [comment]
at least you don't do `feat(cmd(affection*))&fix(cmd(affection*)) fix affection commands`
